import { test, expect, type Page, type Route } from "@playwright/test";
import fs from "fs";
import path from "path";

/**
 * OVERLAY SWEEP at 1440 — every sheet, picker and modal in the requestor and
 * driver flows, opened and photographed.
 *
 * ⚠ THIS HARNESS IS THE DELIVERABLE, NOT THE FIXES. Its job is to answer one
 * question per overlay that source-reading cannot: at 1440, does it cover the
 * form it belongs to, or the primary action?
 *
 * ⚠ IT MUST DISTINGUISH "OPENED AND LOOKS FINE" FROM "NEVER OPENED". A
 * screenshot of an overlay that failed to open is a clean-looking frame of the
 * page behind it, and reporting that as "no problem found" is the failure mode
 * this project has hit repeatedly (see AGENTS.md, ABSENCE LOOKS EXACTLY LIKE
 * SUCCESS). So `capture()` REQUIRES a locator that must be visible first, and
 * records a FAILED-TO-OPEN entry rather than a picture when it is not.
 *
 * Fixture-served: no API, no database, no seeded account.
 *
 *   cd mobile && npx expo start --web --port 8081
 *   cd e2e && npx playwright test overlaySweepShots --config playwright.shots.config.ts
 */

const APP = process.env.E2E_MOBILE_URL ?? "http://localhost:8081";
const SHOTS = path.resolve(__dirname, "../screenshots/overlay-sweep");
const REPORT = path.join(SHOTS, "_report.md");

/** What was observed, written out so the sweep's result is data, not memory. */
const findings: { name: string; opened: boolean; note: string }[] = [];

const REQUESTOR = {
  id: "req-1",
  full_name: "Ng Wei Ling",
  name: "Ng Wei Ling",
  role: "requestor",
  phone: "+60123456789",
  language_pref: "en",
  department_id: "dep-1",
};

const CONSIGNEES = [
  {
    id: "c-1",
    company_name: "Perai Plastics Sdn Bhd",
    area: "Perai",
    state: "Pulau Pinang",
    zone_code: "P2",
    address_1: "12 Jalan Perusahaan",
    postal_code: "13600",
    latitude: 5.3814,
    longitude: 100.3915,
    geocode_match_type: "ROOFTOP",
    is_active: true,
  },
];

// ⚠ RouteType is only { id, name } — the form DERIVES the family and direction
// chips from the NAME (see routeChips in requestor.spec.ts). A fixture named
// just "Customer" renders a family chip and no direction chip, and the run
// stalls waiting for one. Give it the real shape.
const ROUTE_TYPES = [
  { id: "rt-1", name: "Customer Delivery" },
  { id: "rt-2", name: "Customer Return" },
];

async function mockApi(page: Page) {
  await page.route("**/api/v1/**", async (route: Route) => {
    const url = route.request().url();
    const json = (body: unknown) =>
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(body) });

    if (url.includes("/auth/login")) {
      return json({ accessToken: "fixture", refreshToken: "fixture-r", user: REQUESTOR });
    }
    if (url.includes("/users/me") || url.includes("/auth/me")) return json(REQUESTOR);
    if (url.includes("/route-types")) return json(ROUTE_TYPES);
    if (url.includes("/consignees")) return json(CONSIGNEES);
    if (/\/departments(\?|$)/.test(url)) return json([{ id: "dep-1", name: "Logistics" }]);
    if (url.includes("/holidays")) return json([]);
    if (/\/trips(\?|$)/.test(url)) return json([]);
    return json({});
  });
}

async function signIn(page: Page) {
  await mockApi(page);
  await page.goto(APP);
  await page.getByPlaceholder("12-345 6789").fill("123456789");
  await page.getByPlaceholder("Enter your password").fill("fixture");
  await page.getByText("Sign In", { exact: true }).click();
}

/**
 * Photograph an overlay, but ONLY once something inside it is on screen.
 *
 * `proof` is a locator that exists only when the overlay is open. If it never
 * appears, this records a failed-to-open finding and takes a diagnostic shot
 * named `FAILED-*` so the two can never be confused in the output folder.
 */
async function capture(page: Page, name: string, proof: ReturnType<Page["getByText"]>, note = "") {
  try {
    await proof.first().waitFor({ state: "visible", timeout: 12_000 });
  } catch {
    findings.push({ name, opened: false, note: "COULD NOT OPEN — not photographed" });
    await page.screenshot({ path: path.join(SHOTS, `FAILED-${name}.png`) });
    return false;
  }
  await page.waitForTimeout(700);
  await page.screenshot({ path: path.join(SHOTS, `${name}.png`) });
  findings.push({ name, opened: true, note });
  return true;
}

test.use({ viewport: { width: 1440, height: 900 } });

test.describe.configure({ mode: "serial" });

test.beforeAll(() => {
  fs.mkdirSync(SHOTS, { recursive: true });
});

test.afterAll(() => {
  const lines = [
    "# Overlay sweep at 1440",
    "",
    "Generated by `overlaySweepShots.spec.ts`. An entry marked COULD NOT OPEN was",
    "not observed — it is NOT a clean result.",
    "",
    "| overlay | opened | note |",
    "| --- | --- | --- |",
    ...findings.map((f) => `| ${f.name} | ${f.opened ? "yes" : "**NO**"} | ${f.note} |`),
  ];
  fs.writeFileSync(REPORT, lines.join("\n") + "\n", "utf8");
});

test("requestor · pickup picker (wide)", async ({ page }) => {
  await signIn(page);
  await page.getByText("Bookings", { exact: true }).first().waitFor({ timeout: 30_000 });
  await page.getByText("Bookings", { exact: true }).first().click();
  await page.getByLabel("New Booking").click();
  await page.getByText("New Trip Request").waitFor({ timeout: 20_000 });

  // Step 1 — Where. One route type and one consignee in the fixtures.
  await page.getByText("Customer", { exact: true }).first().click();
  await page.getByText("Delivery", { exact: true }).first().click();
  await page.getByPlaceholder("Type company name, area, or location…").fill("Perai");
  // selector-ok: a fixture consignee name, not i18n copy
  const hit = page.getByText("Perai Plastics Sdn Bhd", { exact: true }).locator("visible=true").first();
  await hit.waitFor({ timeout: 10_000 });
  await hit.click();
  await page.getByText("Next", { exact: true }).click();

  // Step 2 — What. One pallet is enough to advance.
  await page.getByText("Cargo Size & Quantity").waitFor({ timeout: 15_000 });
  // selector-ok: the quantity stepper glyph is not a translated string
  await page.getByText("+", { exact: true }).first().click();
  await page.getByText("Next", { exact: true }).click();

  // Step 3 — When. The picker is INLINE here at 1440; there is nothing to open.
  await capture(
    page,
    "requestor-pickup-picker-1440",
    page.getByText("Next: time", { exact: true }),
    "inline wide treatment — no overlay, no dimming"
  );
});
