/**
 * A valid 1×1 JPEG used as the proof-of-delivery photo in the driver completion
 * test. The API just needs a real image file (it forwards the bytes to
 * Cloudinary), so the smallest possible JPEG keeps the upload fast and reliable.
 */
const ONE_BY_ONE_JPEG_B64 =
  "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAj/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABmX/9k=";

export const POD_FILE = {
  name: "pod.jpg",
  mimeType: "image/jpeg",
  buffer: Buffer.from(ONE_BY_ONE_JPEG_B64, "base64"),
};
